### ISSUE TITLE
React can't find 'nid 

### ISSUE THREAD

**Issue by ShaubertIlya** [lightsinthesky/react-node-graph#13]
Hello and good day. I've installed your library and trying to run your example at github. React gives me an issue 'nid' is not defined  no-undef. What can be the problem?

My code

import React, { Component } from 'react';
import ReactNodeGraph from 'react-node-graph';

var exampleGraph = {
  "nodes":[
    {"nid":0,"type":"Timer","x":89,"y":82,"fields":{"in":[{"name":"reset"},{"name":"pause"},{"name":"max"}],"out":[{"name":"out"}]}},
    {"nid":1,"type":"MathMult","x":284,"y":82,"fields":{"in":[{"name":"in"},{"name":"factor"}],"out":[{"name":"out"}]}},
    {"nid":2,"type":"Vector3","x":486,"y":188,"fields":{"in":[{"name":"xyz"},{"name":"x"},{"name":"y"},{"name":"z"}],"out":[{"name":"xyz"},{"name":"x"},{"name":"y"},{"name":"z"}]}}
  ],
  "connections":[
    {"from_node":nid,"from":"field_name","to_node":nid,"to":"field_name"},
  ]
};

class DrawGraph1 extends Component
{
    render()
    {
      return (
        <ReactNodeGraph 
            data={exampleGraph} 
            onNodeMove={(nid, pos)=>this.onNodeMove(nid, pos)}
            onNodeStartMove={(nid)=>this.onNodeStartMove(nid)}
            onNewConnector={(n1,o,n2,i)=>this.onNewConnector(n1,o,n2,i)} 
            onRemoveConnector={(connector)=>this.onRemoveConnector(connector)}
/>
      );

    }
}

export default DrawGraph1;

**Comment by lightsinthesky** [comment]
connections is a collection that is trying to resolve the variable nid which doesnt exist. Change it to 
```
"connections":[
    {"from_node":0,"from":"field_name","to_node":1,"to":"field_name"},
]
```

**Comment by ShaubertIlya** [comment]
It works, thanks. But now it leads to another issue in react-draggable library

TypeError: Cannot read property 'bool' of undefined
defineProperty.value
C:/LocalRepo/graphs_test/graphstest/node_modules/react-draggable/dist/react-draggable.js:1164
  1161 |    *
  1162 |    * Defaults to `false`.
  1163 |    */
> 1164 | 	allowAnyClick: _react.PropTypes.bool,
  1165 | 
  1166 |   /**
  1167 |    * `disabled`, if true, stops the <Draggable> from dragging. All handlers,
